version: '3.3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: r4zeel/foodgram_backend
    env_file: .env
    volumes:
      - media:/app/media
      - static:/app/staticfiles
    depends_on:
      - db
  frontend:
    image: r4zeel/foodgram_frontend
    env_file: .env
    volumes:
      - static:/app/result_build
    depends_on:
      - gateway
  gateway:
    image: r4zeel/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/media
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
