version: '3.3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build:
      context: ../backend/foodgram
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - media:/app/media
      - static:/staticfiles
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static:/result_build
  nginx:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static:/staticfiles
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/media
