version: '3.3'

volumes:
  pg_data:
  media:
  static:
  docs:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: r4zeel/foodgram_backend
    env_file: .env
    volumes:
      - media:/app/media
      - static:/app/staticfiles
      - docs:/app/static/data/docs
    depends_on:
      - db
  frontend:
    image: r4zeel/foodgram_frontend
    env_file: .env
    volumes:
      - static:/app/result_build
    depends_on:
      - gateway
  gateway:
    image: r4zeel/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/media
      # Описан volume для доков и location до них в нгинкс, но они не подгружаются, 
      # со статикой джанго такая-же проблема, при том что в контейнере они сохраняются в корректных папках
      - docs:/docfiles
    depends_on:
      - backend
