# Generated by Django 5.0.3 on 2024-04-12 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='password',
            field=models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150, 'Длина строки не может превышать 150')], verbose_name='Пароль'),
        ),
    ]
