# Generated by Django 5.0.3 on 2024-04-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favoriterecipe_unique_favorite'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique_favorite',
        ),
    ]
